# .goreleaser.yml
version: 2
project_name: lxa

before:
  hooks:
    - go run github.com/cpuguy83/go-md2man/v2@latest -in lxa.1.md -out lxa.1

builds:
  - id: lxa
    main: ./cmd/lxa
    binary: lxa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
    - tar.gz
    files:
      - README.md
      - lxa.1

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
