# .goreleaser.yml
project_name: lxa

builds:
  - id: lxa
    main: ./cmd/lxa
    binary: lxa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
